- project:
    templates:
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
      - publish-to-pypi-horizon
      - translation-jobs-master-stable
    check:
      jobs:
        - nodejs-npm-run-lint:
            vars:
              node_version: 4
            voting: false
        - nodejs-npm-run-test:
            vars:
              node_version: 4
            voting: false
